[build]
  command = "npm install && npm run build"
  publish = "dist/refugio-frontend/browser"

[build.environment]
  NODE_VERSION = "18.18.2"

[[plugins]]
  package = "@netlify/angular-runtime"
  config = { skip = true }

